/**
 * Every conversation state of the deterministic bot state machine.
 * The current state is persisted per phone number in BotSession.
 */
export enum BotState {
  MAIN_MENU = 'MAIN_MENU',

  // Customer management
  CUSTOMER_MENU = 'CUSTOMER_MENU',
  CUSTOMER_ADD_NAME = 'CUSTOMER_ADD_NAME',
  CUSTOMER_ADD_IDENTIFIER = 'CUSTOMER_ADD_IDENTIFIER',
  CUSTOMER_ADD_CONFIRM = 'CUSTOMER_ADD_CONFIRM',

  // Shared customer picker (used by several flows; the `customerPickPurpose`
  // session key decides where to continue after a customer is chosen)
  CUSTOMER_PICK_QUERY = 'CUSTOMER_PICK_QUERY',
  CUSTOMER_PICK_LIST = 'CUSTOMER_PICK_LIST',

  // Selected-customer action menu
  CUSTOMER_ACTIONS = 'CUSTOMER_ACTIONS',

  // Monetary debt / payment
  MONETARY_DEBT_AMOUNT = 'MONETARY_DEBT_AMOUNT',
  MONETARY_DEBT_DESCRIPTION = 'MONETARY_DEBT_DESCRIPTION',
  MONETARY_DEBT_CONFIRM = 'MONETARY_DEBT_CONFIRM',
  MONETARY_PAYMENT_AMOUNT = 'MONETARY_PAYMENT_AMOUNT',
  MONETARY_PAYMENT_DESCRIPTION = 'MONETARY_PAYMENT_DESCRIPTION',
  MONETARY_PAYMENT_CONFIRM = 'MONETARY_PAYMENT_CONFIRM',

  // Product (medicine/fertilizer) debt entry
  PRODUCT_DEBT_CATEGORY = 'PRODUCT_DEBT_CATEGORY',
  PRODUCT_DEBT_ITEM_NAME = 'PRODUCT_DEBT_ITEM_NAME',
  PRODUCT_DEBT_ITEM_QUANTITY = 'PRODUCT_DEBT_ITEM_QUANTITY',
  PRODUCT_DEBT_ITEM_UNIT = 'PRODUCT_DEBT_ITEM_UNIT',
  PRODUCT_DEBT_NOTE = 'PRODUCT_DEBT_NOTE',
  PRODUCT_DEBT_ESTIMATE_CHOICE = 'PRODUCT_DEBT_ESTIMATE_CHOICE',
  PRODUCT_DEBT_ESTIMATE_AMOUNT = 'PRODUCT_DEBT_ESTIMATE_AMOUNT',
  PRODUCT_DEBT_CONFIRM = 'PRODUCT_DEBT_CONFIRM',

  // Product payment (settling product debt items)
  PRODUCT_PAYMENT_PICK_ITEM = 'PRODUCT_PAYMENT_PICK_ITEM',
  PRODUCT_PAYMENT_QUANTITY = 'PRODUCT_PAYMENT_QUANTITY',
  PRODUCT_PAYMENT_AMOUNT = 'PRODUCT_PAYMENT_AMOUNT',
  PRODUCT_PAYMENT_MORE = 'PRODUCT_PAYMENT_MORE',
  PRODUCT_PAYMENT_CONFIRM = 'PRODUCT_PAYMENT_CONFIRM',

  // Seedling order
  SEEDLING_ORDER_PLANT = 'SEEDLING_ORDER_PLANT',
  SEEDLING_ORDER_SEED_GIVEN = 'SEEDLING_ORDER_SEED_GIVEN',
  SEEDLING_ORDER_SEED_PLANT = 'SEEDLING_ORDER_SEED_PLANT',
  SEEDLING_ORDER_SEED_UNIT = 'SEEDLING_ORDER_SEED_UNIT',
  SEEDLING_ORDER_SEED_AMOUNT = 'SEEDLING_ORDER_SEED_AMOUNT',
  SEEDLING_ORDER_DATE_CHOICE = 'SEEDLING_ORDER_DATE_CHOICE',
  SEEDLING_ORDER_NOTE = 'SEEDLING_ORDER_NOTE',
  SEEDLING_ORDER_CONFIRM = 'SEEDLING_ORDER_CONFIRM',

  // Seedling debt (recorded as monetary debt)
  SEEDLING_DEBT_PICK_ORDER = 'SEEDLING_DEBT_PICK_ORDER',
  SEEDLING_DEBT_PLANT = 'SEEDLING_DEBT_PLANT',
  SEEDLING_DEBT_UNIT_PRICE = 'SEEDLING_DEBT_UNIT_PRICE',
  SEEDLING_DEBT_COUNT = 'SEEDLING_DEBT_COUNT',
  SEEDLING_DEBT_CONFIRM = 'SEEDLING_DEBT_CONFIRM',

  // Promissory notes (owner's own debts)
  NOTES_MENU = 'NOTES_MENU',
  NOTE_ADD_PAYEE = 'NOTE_ADD_PAYEE',
  NOTE_ADD_AMOUNT = 'NOTE_ADD_AMOUNT',
  NOTE_ADD_DATE_CHOICE = 'NOTE_ADD_DATE_CHOICE',
  NOTE_ADD_PAST_CONFIRM = 'NOTE_ADD_PAST_CONFIRM',
  NOTE_ADD_NOTE = 'NOTE_ADD_NOTE',
  NOTE_ADD_CONFIRM = 'NOTE_ADD_CONFIRM',
  NOTE_MARK_PAID_PICK = 'NOTE_MARK_PAID_PICK',
  NOTE_MARK_PAID_CONFIRM = 'NOTE_MARK_PAID_CONFIRM',

  // Reports
  REPORTS_MENU = 'REPORTS_MENU',
  REPORT_STATEMENT_RANGE = 'REPORT_STATEMENT_RANGE',

  // Corrections (undo / delete / adjustment)
  CORRECTION_MENU = 'CORRECTION_MENU',
  CORRECTION_UNDO_CONFIRM = 'CORRECTION_UNDO_CONFIRM',
  CORRECTION_DELETE_PICK = 'CORRECTION_DELETE_PICK',
  CORRECTION_DELETE_REASON = 'CORRECTION_DELETE_REASON',
  CORRECTION_DELETE_CONFIRM = 'CORRECTION_DELETE_CONFIRM',
  CORRECTION_ADJUST_DIRECTION = 'CORRECTION_ADJUST_DIRECTION',
  CORRECTION_ADJUST_AMOUNT = 'CORRECTION_ADJUST_AMOUNT',
  CORRECTION_ADJUST_REASON = 'CORRECTION_ADJUST_REASON',
  CORRECTION_ADJUST_CONFIRM = 'CORRECTION_ADJUST_CONFIRM',

  // Shared manual date entry (day -> month -> year); the `dateEntry` session
  // key carries the purpose and decides where the flow continues afterwards
  DATE_ENTRY_DAY = 'DATE_ENTRY_DAY',
  DATE_ENTRY_MONTH = 'DATE_ENTRY_MONTH',
  DATE_ENTRY_YEAR = 'DATE_ENTRY_YEAR',
}
